server:
  port: 8091
  servlet:
    context-path: /coe
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/control_escolar
    username: root
    password: Wilder26?
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update