server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /coa-api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/escuelaBD
    username: postgres
    password: wilder26
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: coa-api
  cloud:
    discovery:
      enabled: true 
eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url: 
   -default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
    
      
