server:
  port: ${random.int(900,9100)}
  servlet:
    context-path: /coa-api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/escuelaBD
    username: postgres
    password: wilder26
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url: 
   -default-zone: http://localhost:8761/eureka/
      
    
      
