spring:
  application:
    name: confi-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WilderTurriza/Sistema-escolar.git
          search-paths: config-data
          default-label: master
server:
  port: 8071
